### PR TITLE
Implement impeller::DisplayListDispatcher::drawTextBlob.

### PR DESCRIPTION
**Pull request by chinmaygarde**

### CODE REVIEW

**Comment by chinmaygarde** [comment]
Sorry about the delay. Wandered down a conceptual dead end for a bit. The solution was much simpler.

**Comment by chinmaygarde** [comment]
Encoder time is pretty high for apps with a huge number of glyphs. I'll implement batching in TextContents in a bit. But this patch is good to go.

**Comment by zanderso** [comment]
> Encoder time is pretty high for apps with a huge number of glyphs. I'll implement batching in TextContents in a bit. But this patch is good to go.

Consider filing an issue for this, and noting it in the code with a TODO.

**Review by zanderso — APPROVED** [review]

**Review by bdero — APPROVED** [review]
Tried this out in gallery and things are looking pretty good! A good chunk of the text disappears but I believe that's due to cached images not being rendered via `drawImage[Rect]` yet.

**Comment by bdero** [comment]
Also, I think the text is getting drawn at the wrong resolution at the moment? It looks like it's half or maybe quarter resolution in gallery.

**Pull request merged**
