### PR TITLE
Delete oversample.exe

### PR DESCRIPTION
**Pull request by Hixie**
Storing executable binaries in the repo is against our security policies. Since this can just be recompiled from the source in the directory, and is in any case merely a demo, it can be safely removed.

### CODE REVIEW

**Review by dnfield — APPROVED** [review]

**Review by chinmaygarde — CHANGES_REQUESTED** [review]
This slipped my mind. I am prepping a patch that removes this dependency. Will be out by EOD. Sorry.

**Comment by chinmaygarde** [comment]
The alternative that gets rid of the dependency completely is here https://github.com/flutter/impeller/pull/46

**Comment by Hixie** [comment]
That works even better. :-)

**Comment by chinmaygarde** [comment]
Wrong link to the PR: https://github.com/flutter/impeller/pull/47

**Pull request closed without merging**
