### PR TITLE
Use New DlPathEffect Object

### PR DESCRIPTION
**Pull request by JsouLiang**
Will unblock https://github.com/flutter/engine/pull/32159
cc @flar @chinmaygarde

### CODE REVIEW

**Comment by chinmaygarde** [comment]
Converting this to a draft till the linked engine patch is reviewed. Thanks.

**Review by chinmaygarde — APPROVED** [review]

**Review by flar — APPROVED** [review]
LGTM

**Comment by JsouLiang** [comment]
cc @chinmaygarde , why the `ci.yaml` always failed?

**Comment by dnfield** [comment]
The CI yaml check can be ignored for this repo. It's something that's getting added automatically but isn't set up for this repo and likely never will be (we'll be moving the contents to flutter/engine before much longer anyway).

**Pull request merged**
