### PR TITLE
Batch all draw calls in the entire text frame.

### PR DESCRIPTION
**Pull request by chinmaygarde**
Also updates comments that were first written when this wasn't batched.

For some reason, in the original implementation, I had assumed that
styling information was not already in a uniform.

### CODE REVIEW

**Review by dnfield — COMMENTED** [review]
Test?

**Comment by chinmaygarde** [comment]
There is no harness today that counts the commands emitted by a `Contents::Render`. For correctness, the existing cases like `AiksTest::CanRenderTextFrame` are present. There is no change in functionality.

**Review by dnfield — APPROVED** [review]

**Comment by dnfield** [comment]
How close are we to running gallery benchmarks?

**Comment by chinmaygarde** [comment]
I suppose you could run the benchmarks now. But since there are missing display list ops, it probably wouldn't be an apples to apples comparison just.

**Comment by chinmaygarde** [comment]
Also, for these kinds of optimizations, I'd rather have a benchmark harness that measures emitted commands by a `Contents::Render` call like I mentioned earlier. Those are more granular and easier to reason about. End to end benchmark harnesses are really hard to maintain but we already have those (like the gallery benches), so I am not excited about adding to that corpus just for Impeller.

**Pull request merged**
